# docker-compose.yml
version: '3.8'

services:
  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - postgres
    networks:
      - sastays-network
    restart: unless-stopped

  # Backend API (you'll need to create this)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://sastays:sastays_password@postgres:5432/sastays_db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - OZOW_SITE_CODE=your-ozow-site-code
      - OZOW_PRIVATE_KEY=your-ozow-private-key
      - PAYFAST_MERCHANT_ID=your-payfast-merchant-id
      - PAYFAST_MERCHANT_KEY=your-payfast-merchant-key
      - PAYFAST_PASSPHRASE=your-payfast-passphrase
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - TWILIO_PHONE_NUMBER=your-twilio-phone
    depends_on:
      - postgres
      - redis
    networks:
      - sastays-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sastays_db
      - POSTGRES_USER=sastays
      - POSTGRES_PASSWORD=sastays_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - sastays-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sastays-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  sastays-network:
    driver: bridge